---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app-deployment
  namespace: portal
  labels:
    app: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      name: portal-app
      labels:
        app: portal
    spec:
      containers:
      - name: portal-container
        image: kosaraju333/portal-spontan-env:V1
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: portal-app-configmap
              key: host
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: portal-app-configmap
              key: port
        - name: USER
          valueFrom:
            secretKeyRef:
              name: portal-app-secrets
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: portal-app-secrets
              key: password
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: portal-app-secrets
              key: database
        - name: listen_PORT
          valueFrom:
            configMapKeyRef:
              name: portal-app-configmap
              key: listen_port
        ports:
        - containerPort: 3000
        # resources:
        #   requests:
        #     memory: 20Mi
        #     cpu: "0.25"
        #   limits:
        #     memory: 400Mi
        #     cpu: "1"