apiVersion: v1
kind: Service
metadata:
  name: portal-app-service
  namespace: portal
spec:
  type: LoadBalancer
  selector:
    app: portal
  ports:
    # Below Port number is a service port number
    - port: 80
      # Below targetPort is a Container Port number
      targetPort: 3000
